<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <title>General System Report</title>
    <style>
        @font-face {
            font-family: 'Cairo';
            src: url('{{ public_path('fonts/Cairo-Regular.ttf') }}') format('truetype');
            font-weight: normal;
            font-style: normal;
        }

        body {
            font-family: 'Cairo', 'DejaVu Sans', sans-serif;
            direction: ltr;
            text-align: center;
            margin: 25px;
            color: #333;
        }

        h1 {
            color: #1a237e;
            margin-bottom: 5px;
            font-size: 22px;
        }

        p {
            margin-top: 0;
            color: #555;
            font-size: 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 25px;
            font-size: 14px;
        }

        th, td {
            border: 1px solid #ccc;
            padding: 10px;
        }

        th {
            background: #f5f5f5;
            color: #000;
        }

        tr:nth-child(even) {
            background: #fafafa;
        }

        .footer {
            margin-top: 40px;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>
<body>

<h1>📊 General System Report</h1>
<p>Summary of key statistics as of {{ now()->format('Y-m-d') }}</p>

<table>
    <thead>
    <tr>
        <th>Metric</th>
        <th>Value</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Total Users</td>
        <td>{{ number_format($stats['total_users'] ?? 0) }}</td>
    </tr>
    <tr>
        <td>Active Users</td>
        <td>{{ number_format($stats['active_users'] ?? 0) }}</td>
    </tr>
    <tr>
        <td>Total Subscriptions</td>
        <td>{{ number_format($stats['total_subscriptions'] ?? 0) }}</td>
    </tr>
    <tr>
        <td>Total Plans</td>
        <td>{{ number_format($stats['total_plans'] ?? 0) }}</td>
    </tr>
    <tr>
        <td>Total Courses</td>
        <td>{{ number_format($stats['total_courses'] ?? 0) }}</td>
    </tr>
    <tr>
        <td>Total Instructors</td>
        <td>{{ number_format($stats['total_instructors'] ?? 0) }}</td>
    </tr>
    <tr>
        <td>Total Payments</td>
        <td>{{ number_format($stats['total_payments'] ?? 0) }}</td>
    </tr>
    <tr>
        <td>Total Revenue</td>
        <td>{{ number_format($stats['total_revenue'] ?? 0, 2) }} EGP</td>
    </tr>
    </tbody>
</table>

<div class="footer">
    This report was automatically generated by the system on {{ now()->format('Y-m-d H:i') }}.
</div>

</body>
</html>
