<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <title>{{ __('reports.instructors_reports') }}</title>
    <style>
        @font-face {
            font-family: 'Cairo';
            src: url('{{ public_path('fonts/Cairo-Regular.ttf') }}') format('truetype');
            font-weight: normal;
            font-style: normal;
        }

        body {
            font-family: 'Cairo', DejaVu Sans, sans-serif;
            direction: ltr;
            text-align: center;
            margin: 25px;
            color: #333;
        }

        h1 {
            color: #1a237e;
            margin-bottom: 5px;
            font-size: 22px;
        }

        p {
            margin-top: 0;
            color: #555;
            font-size: 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 25px;
            font-size: 14px;
        }

        th, td {
            border: 1px solid #ccc;
            padding: 10px;
        }

        th {
            background: #f5f5f5;
            color: #000;
        }

        tr:nth-child(even) {
            background: #fafafa;
        }

        .footer {
            margin-top: 40px;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>
<body>

<h1>Instructors Reports</h1>
<p>Summary of instructors and linked data as of {{ now()->format('Y-m-d') }}</p>

<table>
    <thead>
    <tr>
        <th>#</th>
        <th>{{ __('reports.instructor') }}</th>
        <th>{{ __('reports.courses_count') }}</th>
        <th>{{ __('reports.linked_plans_count') }}</th>
        <th>{{ __('reports.status') }}</th>
    </tr>
    </thead>
    <tbody>
    @foreach($instructors as $instructor)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $instructor->user->full_name ?? '---' }}</td>
            <td>{{ $instructor->courses_count ?? 0 }}</td>
            <td>{{ $instructor->courses->sum('plans_count') ?? 0 }}</td>
            <td>{{ $instructor->is_active ? __('reports.active') : __('reports.inactive') }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<div class="footer">
    This report was automatically generated by the system on {{ now()->format('Y-m-d H:i') }}
</div>

</body>
</html>
